### ISSUE TITLE
Deprecate this crate in favor of indexmap?

### ISSUE THREAD

**Issue by killercup** [contain-rs/linked-hash-map#91]
Just saw [this post](https://bluss.github.io//rust/2018/03/11/the-crate-formerly-known-as-ordermap-tm/) by @bluss announcing indexmap 1.0.

Since linked-hash-map and indexmap seem to solve similar problems, and indexmap is more actively maintained, while linked-hash-map is in maintenance mode, it might be a good idea to officially deprecate this crate.

Not sure if @bluss agrees but indexmap seems like a good candidate for inclusion in the contain-rs orga, too.

**Comment by bluss** [comment]
The whole of contain-rs is dormant, even defunct? It would be nice, but clearer ownership of the crates seems to have worked better..

Note that linked hash map and indexmap have some different properties. Some things indexmap can't match at all (pop front would be a good example).

**Comment by loyd** [comment]
I like indexmap, but some decisions seem too strange.

The most frustrating thing about indexmap is `remove()`, which behaves like `swap_remove()` and breaks the order. Ok, `shift_remove()` has just been [added](https://github.com/bluss/indexmap/pull/99), but its complexity is `O(n)` in order to save indices without holes.

In contract, linked-hash-map has no problems with `remove()`: simple as it should be.

**Comment by bluss** [comment]
The data structure is what it is, we don't blame it for it, we just pick a data structure with the properties fit for the problem.

So maybe it should be clearer what the difference is! Indexmap is not preserving insertion order through every operation, just some. Just like Vec!

This is also the reason some linked hashmap or similar should exist.
